# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JLAudioUnitKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit'
pod 'R.swift'
pod 'Toast-Swift'

 
  # Pods for JLAudioUnitKitDemo

end
