#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform:ios,'15.0'

target:'JLPiHome' do


pod 'LMJHorizontalScrollText'

pod 'FMDB'

pod 'AFNetworking'

pod 'Masonry'

pod 'Colours'

pod 'WMZDialog'

pod 'Bugly', :configurations => ['Release']

pod 'SnapKit'

pod 'RxSwift'

pod 'RxCocoa'

pod 'MarqueeLabel'

pod 'Toast-Swift','~> 5.0.1'

pod 'SwiftyAttributes'

pod 'Starscream'

pod 'SDWebImage'

pod 'MJRefresh'

pod 'DGCharts'

pod 'R.swift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force all pods to iOS 15.0 to avoid simulator SDK 26.0 warnings
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
  
  # 修复 AFNetworking 引用私有头文件 netinet6/in6.h 的问题
  # 在现代 SDK 中 netinet/in.h 已包含所有 IPv6 定义
  af_files = Dir.glob(File.join(installer.sandbox.root, 'AFNetworking', 'AFNetworking', '*.m'))
  af_files.each do |file_path|
    content = File.read(file_path)
    if content.include?('netinet6/in6.h')
      new_content = content.gsub(%r{#import <netinet6/in6\.h>\n}, '')
      File.chmod(0644, file_path)
      File.write(file_path, new_content)
      puts "✓ 已修复: #{File.basename(file_path)}"
    end
  end
                                 
end

