# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKTestHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SDKTestHelper

  pod 'JLUsefulTools','0.0.2'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Colours'
  pod 'MJRefresh'
  pod 'WMZDialog'
  pod 'Toast-Swift','5.0.1'
  pod 'R.swift'
  pod 'FMDB'
  pod 'Starscream'



end
