source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform:ios,'10.0'

target:'NewJieliZhiNeng' do

pod 'LMJHorizontalScrollText'

pod 'FMDB'

pod 'AFNetworking'

pod 'Masonry'

pod 'Colours'

pod 'WMZDialog'

pod 'Bugly'

end

